const vehicles = [
  {name:'Renault Clio', category:'Citadine', price:'250 DH', seats:'5 places', transmission:'Manuelle', fuel:'Essence', image:'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=80', description:'Une citadine pratique et agréable, idéale pour vos déplacements quotidiens et vos escapades.'},
  {name:'Dacia Logan', category:'Berline', price:'280 DH', seats:'5 places', transmission:'Manuelle', fuel:'Essence', image:'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=900&q=80', description:'Une berline spacieuse et fiable qui offre confort et simplicité pour toute la famille.'},
  {name:'Dacia Sandero', category:'Citadine', price:'270 DH', seats:'5 places', transmission:'Manuelle', fuel:'Essence', image:'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80', description:'Un véhicule polyvalent, économique et confortable pour vos trajets à Oulad Teima et au-delà.'}
];
const grid=document.querySelector('#vehicle-grid');
const featureIcon={seats:'♙',transmission:'⚙',fuel:'◉'};
grid.innerHTML=vehicles.map((v,i)=>`<article class="vehicle-card reveal"><div class="vehicle-image"><img src="${v.image}" alt="${v.name} en location chez HRS CAR" loading="lazy"><span class="category">${v.category}</span></div><div class="vehicle-info"><div class="vehicle-title"><h3>${v.name}</h3><span class="price">Dès ${v.price}<small> / jour</small></span></div><div class="features"><span>${featureIcon.seats} ${v.seats}</span><span>${featureIcon.transmission} ${v.transmission}</span><span>${featureIcon.fuel} ${v.fuel}</span><span>❄ Climatisation</span></div><button class="details-link" data-vehicle="${i}">Voir les détails&nbsp; →</button></div></article>`).join('');
const modal=document.querySelector('#vehicle-modal');
const modalContent=document.querySelector('#modal-content');
function showVehicle(i){const v=vehicles[i];modalContent.innerHTML=`<img class="modal-image" src="${v.image}" alt="${v.name}"><div class="modal-body"><p class="eyebrow">${v.category} · HRS CAR</p><h2>${v.name}</h2><strong class="price">À partir de ${v.price} / jour</strong><div class="features"><span>♙ ${v.seats}</span><span>⚙ ${v.transmission}</span><span>◉ ${v.fuel}</span><span>❄ Climatisation</span></div><p>${v.description}</p><form id="modal-booking"><div class="form-row"><label>Date de départ<input required type="date"></label><label>Date de retour<input required type="date"></label></div><button class="button" type="submit">Demander une réservation <span>→</span></button><p class="form-note" id="modal-message"></p></form></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.querySelector('#modal-booking').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#modal-message').textContent='Votre demande est prête. Contactez HRS CAR pour confirmer la disponibilité.'});}
grid.addEventListener('click',e=>{const button=e.target.closest('[data-vehicle]');if(button)showVehicle(button.dataset.vehicle)});
document.querySelector('.modal-close').addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
document.querySelector('.menu-toggle').addEventListener('click',e=>{const links=document.querySelector('.nav-links');const open=links.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav-links').classList.remove('open')));
window.addEventListener('scroll',()=>document.querySelector('.site-header').classList.toggle('scrolled',scrollY>40));
document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#search-message').textContent='Merci ! Consultez nos véhicules ci-dessous et envoyez-nous votre demande.';document.querySelector('#voitures').scrollIntoView({behavior:'smooth'})});document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#contact-message').textContent='Merci pour votre demande. HRS CAR vous répondra prochainement.';e.target.reset()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal, .benefit-grid article, .service-grid article, .review-grid article').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
const today=new Date().toISOString().split('T')[0];document.querySelectorAll('input[type=date]').forEach(input=>input.min=today);
